[versions]
groovy = "2.5.8"
workflowCps = "4043.va_fb_de6a_a_8b_f5"
workflowSupport = "961.v51869f7b_d409"

[libraries]
groovy = { group = "org.codehaus.groovy", name = "groovy-all", version.ref = "groovy" }
jenkins-workflow-cps = { group = "org.jenkins-ci.plugins.workflow", name = "workflow-cps", version.ref = "workflowCps" }
jenkins-workflow-suport = { group = "org.jenkins-ci.plugins.workflow", name = "workflow-support", version.ref = "workflowSupport" }
